# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Books_Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Authors')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.Books')),
            ],
            options={
                'ordering': ['-user'],
            },
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(through='battle.Books_Authors', to='battle.Authors'),
        ),
        migrations.AlterUniqueTogether(
            name='books_authors',
            unique_together=set([('book', 'author')]),
        ),
    ]
